namespace Application.System.MasterData.Company.Dtos
{
    public sealed record CreateCompanyDto(
        string Code,
        string? EngName,
        string? ArbName,
        string? ArbName4S,
        bool? IsHigry,
        bool? IncludeAbsencDays,
        string? EmpFirstName,
        string? EmpSecondName,
        string? EmpThirdName,
        string? EmpFourthName,
        string? EmpNameSeparator,
        string? Remarks,
        int? RegUserId,
        int? regComputerId,
        int? PrepareDay,
        string? DefaultTheme,
        bool? VacationIsAccum,
        bool? HasSequence,
        int? SequenceLength,
        int? Prefix,
        string? Separator,
        byte? SalaryCalculation,
        bool? DefaultAttend,
        bool? CountEmployeeVacationDaysTotal,
        bool? ZeroBalAfterVac,
        bool? VacSettlement,
        bool? AllowOverVacation,
        bool? VacationFromPrepareDay,
        int? ExecuseRequestHoursallowed,
        bool? EmployeeDocumentsAutoSerial,
        bool? UserDepartmentsPermissions
    );
}