namespace Application.System.MasterData.Project.Dtos
{
    public sealed record CreateProjectDto(
        string Code,
        string EngName,
        string ArbName,
        string? ArbName4S,
        string? Phone,
        string? Mobile,
        string? Fax,
        string? Email,
        string? Adress,
        string? ContactPerson,
        int? ProjectPeriod,
        int? ClaimDuration,
        DateTime? StartDate,
        DateTime? EndDate,
        decimal? CreditLimit,
        int? CreditPeriod,
        bool? IsAdvance,
        bool? IsHijri,
        int? NotifyPeriod,
        string? CompanyConditions,
        string? ClientConditions,
        bool? IsLocked,
        bool? IsStoped,
        int? BranchId,
        string? Remarks,
        string? WorkConditions,
        int? LocationId,
        int? AbsentTransaction,
        int? LeaveTransaction,
        int? LateTransaction,
        int? SickTransaction,
        int? OTTransaction,
        int? HOTTransaction,
        string? CostCenterCode1,
        int? DepartmentId,
        string? CostCenterCode2,
        string? CostCenterCode3,
        string? CostCenterCode4,
        int? RegComputerId
    );
}