namespace Application.System.HRS.VacationAndEndOfService.VacationsType.Dtos
{
    public sealed record VacationsTypeDto(
        int Id,
        string Code,
        string? EngName,
        string? ArbName,
        string? ArbName4S,
        short? IsPaid,
        string? Sex,
        bool? IsAnnual,
        bool? IsSickVacation,
        bool? IsFromAnnual,
        int? ForSalaryTransaction,
        int CompanyId,
        string? CompanyName,
        string? Remarks,
        int? OBalanceTransactionId,
        int? OverDueVacationId,
        float? Stage1Pct,
        float? Stage2Pct,
        float? Stage3Pct,
        int? ForDeductionTransaction,
        bool? AffectEos,
        int? VactionTypeCaculation,
        int? ExceededDaysType,
        bool? HasPayment,
        bool? RoundAnnualVacBalance,
        string? Religion,
        bool? IsOfficial,
        bool? OverlapWithAnotherVac,    
        bool? ConsiderAllowedDays,
        int? TimesNoInYear,
        int? AllowedDaysNo,
        bool? ExcludedFromSsRequests,
        DateTime RegDate,
        DateTime? CancelDate,
        bool IsActive
    );
}